name: Deploy Analysis Notebook
on:
  push:
    branches:
      - deploy-rmd

jobs:
  build-book:
    name: Render-Book
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1


      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Render and build book
        run: |
          renv::restore()
          devtools::load_all()
          rmarkdown::render("./heterogeneity-analysis.Rmd", output_dir = "markdown-outputs", output_file = "index.html")          

        shell: Rscript {0}
      - name: Init new repo in book/_book folder and commit generated files
        run: |
          cd markdown-outputs/
          git init
          git add -A
          git config --local user.email "lgorman@turing.ac.uk"
          git config --local user.name "l-gorman"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          # Token for the repo
          # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.PUBLISHNOTEBOOK }}
          # Destination branch to push changes
          branch: gh-pages
          # Force the changes through
          force: true
          # Change to the build directory before pushing
          directory: ./markdown-outputs
          repository: "l-gorman/farm-size-analysis"
          